/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppShowcaseRouteImport } from './routes/_app.showcase'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppContactRouteImport } from './routes/_app.contact'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShowcaseRoute = AppShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof AppContactRoute
  '/home': typeof AppHomeRoute
  '/pricing': typeof AppPricingRoute
  '/showcase': typeof AppShowcaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof AppContactRoute
  '/home': typeof AppHomeRoute
  '/pricing': typeof AppPricingRoute
  '/showcase': typeof AppShowcaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/contact': typeof AppContactRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/showcase': typeof AppShowcaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/home' | '/pricing' | '/showcase'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/home' | '/pricing' | '/showcase'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/contact'
    | '/_app/home'
    | '/_app/pricing'
    | '/_app/showcase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/showcase': {
      id: '/_app/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof AppShowcaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContactRoute: typeof AppContactRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPricingRoute: typeof AppPricingRoute
  AppShowcaseRoute: typeof AppShowcaseRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactRoute: AppContactRoute,
  AppHomeRoute: AppHomeRoute,
  AppPricingRoute: AppPricingRoute,
  AppShowcaseRoute: AppShowcaseRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
